# .github/workflows/sync_to_hub.yml
name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Por si acaso añades archivos grandes en el futuro
          
      - name: Sincronizar con Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Usamos el nombre de usuario y el nombre del Space que me has pasado
          git push https://jmartinezsegulagrp:$HF_TOKEN@huggingface.co/spaces/jmartinezsegulagrp/TW HEAD:main -f